### ISSUE TITLE
Use metadata filter in search?

### ISSUE THREAD

**Issue by galtay-tempus** [bclavie/RAGatouille#11]
Does the ColBERT implementation here (or elsewhere) allow for indexing and filtering documents by metadata? For example, something like, 

```python
results = RAG.search(query, filter={"doc_type": "doc_type_im_interested_in"})
```

**Comment by bclavie** [comment]
Hey! ColBERT natively doesn't support this (its main job is really embedding/creating individual index). I believe Vespa (cc @jobergum) would be the best way to use ColBERT with filtering!

**Comment by bclavie** [comment]
Something worth noting however, since ColBERT's retrieval scales in pretty-much constant time (see @okhat's excellent [thread](https://twitter.com/lateinteraction/status/1737578879454425202) explaining this), retrieving from the full document index with a high `k` and filtering the results is an option that could be viable in most cases!

**Comment by galtay-tempus** [comment]
thanks for the info!
