### ISSUE TITLE
max_document_length cannot exceed 512

### ISSUE THREAD

**Issue by bigodyssey** [bclavie/RAGatouille#124]
`RAG.index(
    collection=ragatouille_docs,
    index_name="book01",
    max_document_length=600,
    split_documents=True,
)`
Set max_document_length smaller than 512, it works.
RuntimeError: The expanded size of the tensor (600) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [64, 600].  Tensor sizes: [1, 514]

**Comment by Akshay1921** [comment]
Bert has a max_length of 512 , recommended value is 128,256.

**Comment by bclavie** [comment]
Hey, right now it's hard-coded as 512 because all existing ColBERT models are spun off models with a 512 max length. This is not ideal and I'm planning on making it so:
- There are clearer indications of that being printed
- Max length doesn't cap at 512 but at the max length of your underlying base model (to support longer context length models which people are now training)

**Comment by bigodyssey** [comment]
thx!

**Comment by bclavie** [comment]
FYI the hard 512 limit is fixed with https://github.com/bclavie/RAGatouille/pull/132. There's people currently training 8192 seqlen ColBERT which will be supported out of the box after this is merged!
