### ISSUE TITLE
Support for optional documents metadata like "source file", "date created" etc. while indexing, to show them when searching

### ISSUE THREAD

**Issue by tm17-abcgen** [bclavie/RAGatouille#25]
Got a short question, is it possible to embed sources as metadata into the documents when indexing (as option), so that after retrieval with RAG.search, one can see from which source the relevant documents are (as option)?

**Comment by bclavie** [comment]
Hey!

We don't currently support this, but it'd be relatively simple to add (though take more space on-disk!).

Right now, when an independent is create, we also export a `collection.json`, which contains all the documents inside it. This is useful so we can return the document: the index only store the passage ids (they correspond to the indices in the list contained in `collection.json`)

Apart from limited time, there's nothing stopping us from also storing a `metadata.json` file, which would be a list of dictionaries (or of a `Metadata` Pedantic object exported to dict, for easier validation), where the entry at index `i` would contain the metadata associated with passage_id `i`. 

If you'd like to implement this, feel free! Otherwise it's definitely on the list of nice-to-have features that we'll circle to eventually.

**Comment by anirudhdharmarajan** [comment]
I'm taking a stab at this [here](https://github.com/anirudhdharmarajan/RAGatouille/tree/custom-metadata).

I'll finish up the tests in the next day or so, and open a PR.

**Comment by LarsAC** [comment]
Ouch, saw this issue yesterday and started planning an implementation. Just got started so almost saw your note in time @anirudhdharmarajan ...

**Comment by 0-hero** [comment]
Looking forward for your implementation. @anirudhdharmarajan

**Comment by anirudhdharmarajan** [comment]
PR's up, would love any feedback on the approach I took for this (and a couple other related things that got pulled in 😅

**Comment by bclavie** [comment]
Live in 0.0.5a thanks to @anirudhdharmarajan's amazing work!

cc @LarsAC @0-hero @tm17-abcgen

**Comment by 0-hero** [comment]
Thankyou, just raised a PR on llama-hub too https://github.com/run-llama/llama-hub/pull/893
