### ISSUE TITLE
Version of python being used ?

### ISSUE THREAD

**Issue by NitinAggarwal1** [bclavie/RAGatouille#27]
Some dependant library is failing. Please specify the version you are using . 

ImportError: cannot import name 'Iterator' from 'typing_extensions' (/opt/conda/lib/python3.10/site-packages/typing_extensions.py)

**Comment by timothepearce** [comment]
I tried Python 3.11 and 3.10, and they both worked. Your problems seem related to your conda env; the `typing` module has been available since Python 3.5.

**Comment by NitinAggarwal1** [comment]
Any working solution to the typing module problems in conda you can refer.

**Comment by bclavie** [comment]
Hey!

Thanks @timothepearce for answering. RAGatouille supports >=3.9, I'll update the README soon to make it clearer.

The issue you're having is somewhat common with conda, there's a lot of similar issues all over GitHub (e.g. a similar one here https://github.com/tiangolo/fastapi/discussions/9808).

The issue seems to be that there can be conflicting versions of typing_extensions installed at the system level & in the conda env, and also by pypi, or by conda. This is compounded because the library is sometimes called `typing_extensions` or `typing-extensions`, but is always imported via `from typing_extensions [...]`. I'll eventually try to see if I can figure out a way for it to be force-installed when installing RAGatouille.

I think for now this should solve your issue (one of the `uninstall` might fail, don't worry about it!):

```bash
pip uninstall typing_extensions
pip uninstall typing-extensions
pip install --upgrade typing-extensions
```

**Comment by mlkorra** [comment]
@bclavie can you update the README with minimum python version required to setup RAGatouille, I was using 3.8.10 and had trouble installing it and found the python requirement here.
